### ISSUE TITLE
402,403 Can Not Run

### ISSUE THREAD

**Issue by hanghang2333** [MorvanZhou/Tensorflow-Tutorial#1]
ok,还是用中文描述吧。应该是tensorflow版本更新的问题，在tensorflow1.1.0下这两个例子不能运行，当我降到tensorflow1.0.0时就可以了。
报错的内容是:ValueError: Attempt to have a second RNNCell use the weights of a variable scope that already has weights: 'Model/RNN/multi_rnn_cell/cell_0/basic_lstm_cell'; and the cell was not constructed as BasicLSTMCell(..., reuse=True). To share the weights of an RNNCell, simply reuse it in your second calculation, or create a new one with the argument reuse=True.

代码应该是正确的，只是版本的问题。但是按照网上查到的解决办法都不能正常运行。sad。
不知道莫凡老师知道在1.1.0版本下如何修改这个例子能够正常运行吗?谢谢了。

**Comment by MorvanZhou** [comment]
Please specify the problems, otherwise, I cannot help.

**Comment by hanghang2333** [comment]
已更新详细，谢谢 @MorvanZhou

**Comment by MorvanZhou** [comment]
@hanghang2333 请问你是用 Windows 吗? 因为我用 mac, tf1.1.0 没有这个问题. 可能是tf 自身的 bug

**Comment by hanghang2333** [comment]
@MorvanZhou 这样，我用的是ubuntu16.04。
