### ISSUE TITLE
Add the version description at 'tutorial-contents/306_dataset.py'

### ISSUE THREAD

**Issue by gglinux** [MorvanZhou/Tensorflow-Tutorial#12]
Tensorflow-Tutorial/tutorial-contents/306_dataset.py line:9

In tensorFlow 1.3, get Dataset like 'from tensorflow.contrib.data import Dataset'.
But in 1.2 or other version, we can't get Dataset like that.
Please add the description, the newbie will be grateful.

**Comment by MorvanZhou** [comment]
Updated with thanks
