### ISSUE TITLE
transfer learning

### ISSUE THREAD

**Issue by xiatutu** [MorvanZhou/Tensorflow-Tutorial#14]
您好，这个教程中有l两个不明白的地方。
1.如何控制卷积层的参数是固定不变，不在训练时候被改变的。。
CNN's filter is constant, NOT Variable that can be trained

2.如果需要微调卷积层的参数应该怎么改?

**Comment by MorvanZhou** [comment]
只要你的filter 不是variable，而是constant，在训练的时候就不被训练。如果要微调，就需要在filter上包一层 Variable。`filter = tf.Variable(filter)`, 同样 bias也要这样操作 `bias = tf.Variable(bias)`

**Comment by xiatutu** [comment]
太谢谢了~祝小哥哥工作顺利~
