### ISSUE TITLE
406Gan

### ISSUE THREAD

**Issue by xiaoyaosheng** [MorvanZhou/Tensorflow-Tutorial#15]
D_loss = -tf.reduce_mean(tf.log(prob_artist0) + tf.log(1-prob_artist1))
G_loss = tf.reduce_mean(tf.log(1-prob_artist1))
这个损失函数能将下是什么含义吗

**Comment by MorvanZhou** [comment]
请参考这一个篇我写的教程。https://morvanzhou.github.io/tutorials/machine-learning/torch/4-06-GAN/ 虽然是用pytorch写的，但是代码结构和tensorflow的一模一样
