### ISSUE TITLE
frequency and shortcut to update tensorflow from source?

### ISSUE THREAD

**Issue by EmbraceLife** [MorvanZhou/Tensorflow-Tutorial#2]
Hi Morvan, 

Basically, to update tensorflow after installed from source,  is to re-install from source, there is no shortcut, right? 

Also, given it takes a while to install from source, how often it is recommended to re-install from source? 

Thanks!

**Comment by MorvanZhou** [comment]
It sounds right. I haven't found another shortcut yet. If you don't mind the speed and want to upgrade frequently, I don't recommend installing from source. It takes me 30-60mins to install. So in this case, a simple "pip" install is good enough.
