### ISSUE TITLE
403_RNN_regression ups bug!!

### ISSUE THREAD

**Issue by ucasiggcas** [MorvanZhou/Tensorflow-Tutorial#21]
Dear,
When run the [script](https://github.com/MorvanZhou/Tensorflow-Tutorial/blob/master/tutorial-contents/403_RNN_regression.py),
Error ups,

WARNING:tensorflow:From D:\python\LogisticRegression-master\403_RNN_regression.py:32: BasicRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.SimpleRNNCell, and will be replaced by that in Tensorflow 2.0.

How to solve the question?
Could U help me ,please ?
Thx

**Comment by MorvanZhou** [comment]
Please use this tf.nn.rnn_cell.RNNCell instead https://www.tensorflow.org/versions/r1.8/api_docs/python/tf/contrib/rnn/RNNCell?hl=en

**Comment by ucasiggcas** [comment]
> tf.nn.rnn_cell.RNNCel

Not so easy，

Also error

`Traceback (most recent call last):
  File "D:\python\LogisticRegression-master\403_RNN_regression.py", line 32, in <module>
    rnn_cell = tf.nn.rnn_cell.RNNCell(num_units=CELL_SIZE)
  File "D:\python\lib\site-packages\tensorflow\python\ops\rnn_cell_impl.py", line 198, in __init__
    trainable=trainable, name=name, dtype=dtype, **kwargs)
  File "D:\python\lib\site-packages\tensorflow\python\layers\base.py", line 84, in __init__
    **kwargs)
  File "D:\python\lib\site-packages\tensorflow\python\training\checkpointable\base.py", line 474, in _method_wrapper
    method(self, *args, **kwargs)
  File "D:\python\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 138, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', 'num_units')`

**Comment by MorvanZhou** [comment]
The tensorflow API keeps changing, tf.nn.rnn_cell.BasicRNNCell this would be the one that works. https://www.tensorflow.org/api_docs/python/tf/nn/rnn_cell/BasicRNNCell?hl=en

**Comment by ucasiggcas** [comment]
Warning again：

`WARNING:tensorflow:From D:\python\LogisticRegression-master\403_RNN_regression.py:32: BasicRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.SimpleRNNCell, and will be replaced by that in Tensorflow 2.0.`

If I use the
**tf.keras.layers.SimpleRNNCell**，Bug ups

`Traceback (most recent call last):
  File "D:\python\LogisticRegression-master\403_RNN_regression.py", line 32, in <module>
    rnn_cell =  tf.keras.layers.SimpleRNNCell(num_units=CELL_SIZE)
TypeError: __init__() missing 1 required positional argument: 'units'`
