### ISSUE TITLE
what is the difference between tf.contrib.layers  an tf.layers ?

### ISSUE THREAD

**Issue by lizhengwei1992** [MorvanZhou/Tensorflow-Tutorial#3]
such as tf.contrib.layers.batch_norm / tf.layers.batch_normalization,...

**Comment by MorvanZhou** [comment]
I think they are pretty much the same. tf.contrib.layers may be the higher wrapper for tf.layers, and contrib consists of many other functions than layers. However, I think tf.layers should be the core function, while the contrib has the function built on the core functions, so functions in contrib may change in the future.
