### ISSUE TITLE
About the training of autoencoder

### ISSUE THREAD

**Issue by songzenghui** [MorvanZhou/Tensorflow-Tutorial#6]
Does the stacked autoencoder need pre-training or fine-tune?I see your code that your AE does not have pre-training or fine-tune.Did the process be executed in some function that TF has?

**Comment by MorvanZhou** [comment]
The stacked autoencoder has a different training procedure than the autoencoder. It has to be trained at the first place layer by layer. Have a look at [this tutorial](http://ufldl.stanford.edu/wiki/index.php/Stacked_Autoencoders) and you will find some ideas of it. After you know the procedure, using TF to make it becomes much easy.
