### ISSUE TITLE
303_save_reload.py can not run.

### ISSUE THREAD

**Issue by XiaXuehai** [MorvanZhou/Tensorflow-Tutorial#7]
`saver.save(sess, 'params', write_meta_graph=False)  # meta_graph is not recommended`
`'params'` must be modified to` 'my_net/params'`.

**Comment by xunge** [comment]
I have the same problem when it runs in windows, but it is normal when run in mac OS.

**Comment by MorvanZhou** [comment]
I have updated the code regarding this issue.
