### ISSUE TITLE
load iamge

### ISSUE THREAD

**Issue by AdamKingsley** [MorvanZhou/Tensorflow-Tutorial#8]
利用transfer learning的代码处理一批图片， 发现调用了一张图片，最后resize出现了224*224*4的格式，导致输入神经网络的数据格式报错(VGG 要224*224*3的size) 
新手勿喷，想问这是什么原因？

**Comment by Segregation** [comment]
图片有alpha通道了吧，去掉就好了

**Comment by AdamKingsley** [comment]
哦哦，懂了
