### ISSUE TITLE
img/255

### ISSUE THREAD

**Issue by AdamKingsley** [MorvanZhou/Tensorflow-Tutorial#9]
transfer_learning中load image为什么需要img/255呢?

**Comment by cmjdxy** [comment]
因为是灰度图像，这样做就把图像灰度值限制到了0-1之间，有点batch normalization的意思。详情可参考这篇文章：https://arxiv.org/pdf/1502.03167.pdf
不过我自己试验的时候，发现加不加这个归一化好像区别不大（数据集是MNIST）。

**Comment by AdamKingsley** [comment]
emm，所以说如果是与处理图片然后输入到VGG中的话，灰度化会让训练结果变得更好是吗？是不是一般来讲CNN进行训练图像的话最好 都要进行图像的 灰度化处理呢?

**Comment by cmjdxy** [comment]
这个不太确定，看你用的数据集和网络结构吧。其实你两种都试试也好，加或不加还是看效果，毕竟加这个操作也不太费事。
